### ISSUE TITLE
STATIC doesn't serve on production.

### ISSUE THREAD

**Issue by brandenvs** [StadPrin/website#10]
Could we please address this issue before the end of the week? _I want to update the logo next week, and the site needs to be ready._

**Comment by DylanPrinsloo** [comment]
Saw this check-in 

Let me know if you need anything from me.

**Comment by brandenvs** [comment]
> Saw this check-in
> 
> Let me know if you need anything from me.

No stress; I have created the branch for issue #10. Busy with upgrades, it's always tricky to get right with UNIX permissions, leading to ambiguous 403 errors. But the good news is once we solve the problem on the production server, we won't have to worry about solving things again.

*PS I'll close this issue once I merge the issuing branch with the main.*
