### ISSUE TITLE
README.md needs some TLC

### ISSUE THREAD

**Issue by brandenvs** [StadPrin/website#5]
## Please complete the following objectives in order to close this issue

- [x] #6
- [x] #7
- [x] #8

---

The read me for the main branch should represent **The main project and original motive behind opening the repository**. Then, the repository can be adapted as we see fit. Still, right now, we need to start applying standards to the work we produce. 

_We can open the discussion and see which practice we want to implement across our work and define it in a table of sorts._

---

_Kind regards_,
Branden v Staden

**Comment by DylanPrinsloo** [comment]
I'll get this on. 

I'll work on it and ask you for guidance along the way.

**Comment by brandenvs** [comment]
Done
