### ISSUE TITLE
Update main objectives to the latest and,

### ISSUE THREAD

**Issue by brandenvs** [StadPrin/website#7]
*Please include the following objective:*

1. Frontend:
   1. `Landing` - *HTML, CSS & JS Webpage.*
   2. `Contact us` - *HTML, CSS & JS Webpage.*
   3. `About us` - *HTML, CSS & JS Webpage.*
2. Backend:
   1. Ubuntu Linux 22.04 LTS webserver configuration,
   2. Secure/Proper deployment of Django web application and,
   3. *Cross-sync between production and development environment using GitHub version control*.
3. DevOps
   1. Deploy solution,
   2. Develop necessary elements and update the repository, and,
   3. Test redeploy.

Feel free to add objectives to the list by following the format or segmenting it into two separate lists. Additionally, take note of the markdown code for this file by inspecting it and observing how I've laid out and used the markdown language. There is a lot of discussion to have regarding markdown, but for now, just take a look at the following online resource: [Markdown Guide(syntax)](https://www.markdownguide.org/basic-syntax/).

---

*Kind regards,*
Branden v Staden.

**Comment by DylanPrinsloo** [comment]
Ill continue with the navbar, I'm going to work on learning to push code to the repo!

**Comment by brandenvs** [comment]
Great! Thank you for self-assigning. _Feel free to add any relevant planning and design._

**Comment by DylanPrinsloo** [comment]
Good evening I’m going to do some work on the website tomorrow. Let me know if you keen to do a hour sprint.Best wishes Dylan On 17 May 2024, at 18:15, Branden v Staden ***@***.***> wrote:﻿
Great! Thank you for self-assigning. Feel free to add any relevant planning and design.
